/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f2_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[5] = {1, 1, 0, 1, 0};

/* f2:(theta,dtheta,ddtheta,phi,dphi,ddphi,tau,g)->(f2) */
static int casadi_f0(casadi_real* arg, casadi_real* res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8;
  /* #0: @0 = 12533556 */
  w0 = 12533556.;
  /* #1: @1 = input[4][0] */
  w1 = arg[4] ? arg[4] : 0;
  /* #2: @2 = sq(@1) */
  w2 = casadi_sq( w1 );
  /* #3: @0 = (@0*@2) */
  w0 *= w2;
  /* #4: @2 = input[3][0] */
  w2 = arg[3] ? arg[3] : 0;
  /* #5: @3 = (2.*@2) */
  w3 = (2.* w2 );
  /* #6: @3 = sin(@3) */
  w3 = sin( w3 );
  /* #7: @0 = (@0*@3) */
  w0 *= w3;
  /* #8: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #9: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #10: @0 = (@0*@3) */
  w0 *= w3;
  /* #11: @3 = 92330757 */
  w3 = 92330757.;
  /* #12: @4 = input[1][0] */
  w4 = arg[1] ? arg[1] : 0;
  /* #13: @5 = sq(@4) */
  w5 = casadi_sq( w4 );
  /* #14: @3 = (@3*@5) */
  w3 *= w5;
  /* #15: @5 = (2.*@2) */
  w5 = (2.* w2 );
  /* #16: @5 = sin(@5) */
  w5 = sin( w5 );
  /* #17: @3 = (@3*@5) */
  w3 *= w5;
  /* #18: @0 = (@0-@3) */
  w0 -= w3;
  /* #19: @3 = 50000000 */
  w3 = 50000000.;
  /* #20: @5 = input[6][0] */
  w5 = arg[6] ? arg[6] : 0;
  /* #21: @3 = (@3*@5) */
  w3 *= w5;
  /* #22: @6 = cos(@2) */
  w6 = cos( w2 );
  /* #23: @3 = (@3*@6) */
  w3 *= w6;
  /* #24: @0 = (@0-@3) */
  w0 -= w3;
  /* #25: @3 = 135105000 */
  w3 = 135105000.;
  /* #26: @6 = input[7][0] */
  w6 = arg[7] ? arg[7] : 0;
  /* #27: @3 = (@3*@6) */
  w3 *= w6;
  /* #28: @7 = sin(@2) */
  w7 = sin( w2 );
  /* #29: @3 = (@3*@7) */
  w3 *= w7;
  /* #30: @0 = (@0-@3) */
  w0 -= w3;
  /* #31: @3 = 36680000 */
  w3 = 36680000.;
  /* #32: @7 = sq(@1) */
  w7 = casadi_sq( w1 );
  /* #33: @3 = (@3*@7) */
  w3 *= w7;
  /* #34: @7 = cos(@2) */
  w7 = cos( w2 );
  /* #35: @8 = 3 */
  w8 = 3.;
  /* #36: @7 = pow(@7,@8) */
  w7  = pow(w7,w8);
  /* #37: @3 = (@3*@7) */
  w3 *= w7;
  /* #38: @7 = input[0][0] */
  w7 = arg[0] ? arg[0] : 0;
  /* #39: @8 = sin(@7) */
  w8 = sin( w7 );
  /* #40: @3 = (@3*@8) */
  w3 *= w8;
  /* #41: @0 = (@0-@3) */
  w0 -= w3;
  /* #42: @3 = 49556514 */
  w3 = 49556514.;
  /* #43: @3 = (@3*@1) */
  w3 *= w1;
  /* #44: @3 = (@3*@4) */
  w3 *= w4;
  /* #45: @8 = (2.*@7) */
  w8 = (2.* w7 );
  /* #46: @8 = sin(@8) */
  w8 = sin( w8 );
  /* #47: @3 = (@3*@8) */
  w3 *= w8;
  /* #48: @0 = (@0-@3) */
  w0 -= w3;
  /* #49: @3 = 24778257 */
  w3 = 24778257.;
  /* #50: @8 = sq(@1) */
  w8 = casadi_sq( w1 );
  /* #51: @3 = (@3*@8) */
  w3 *= w8;
  /* #52: @8 = (2.*@2) */
  w8 = (2.* w2 );
  /* #53: @8 = sin(@8) */
  w8 = sin( w8 );
  /* #54: @3 = (@3*@8) */
  w3 *= w8;
  /* #55: @0 = (@0-@3) */
  w0 -= w3;
  /* #56: @3 = 46703556 */
  w3 = 46703556.;
  /* #57: @8 = sq(@4) */
  w8 = casadi_sq( w4 );
  /* #58: @3 = (@3*@8) */
  w3 *= w8;
  /* #59: @8 = (2.*@2) */
  w8 = (2.* w2 );
  /* #60: @8 = sin(@8) */
  w8 = sin( w8 );
  /* #61: @3 = (@3*@8) */
  w3 *= w8;
  /* #62: @8 = cos(@2) */
  w8 = cos( w2 );
  /* #63: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #64: @3 = (@3*@8) */
  w3 *= w8;
  /* #65: @0 = (@0+@3) */
  w0 += w3;
  /* #66: @3 = 50000000 */
  w3 = 50000000.;
  /* #67: @8 = sq(@1) */
  w8 = casadi_sq( w1 );
  /* #68: @3 = (@3*@8) */
  w3 *= w8;
  /* #69: @8 = cos(@2) */
  w8 = cos( w2 );
  /* #70: @3 = (@3*@8) */
  w3 *= w8;
  /* #71: @8 = sin(@2) */
  w8 = sin( w2 );
  /* #72: @3 = (@3*@8) */
  w3 *= w8;
  /* #73: @0 = (@0+@3) */
  w0 += w3;
  /* #74: @3 = 68340000 */
  w3 = 68340000.;
  /* #75: @3 = (@3*@6) */
  w3 *= w6;
  /* #76: @6 = cos(@2) */
  w6 = cos( w2 );
  /* #77: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #78: @3 = (@3*@6) */
  w3 *= w6;
  /* #79: @6 = sin(@2) */
  w6 = sin( w2 );
  /* #80: @3 = (@3*@6) */
  w3 *= w6;
  /* #81: @0 = (@0+@3) */
  w0 += w3;
  /* #82: @3 = 18340000 */
  w3 = 18340000.;
  /* #83: @6 = sq(@1) */
  w6 = casadi_sq( w1 );
  /* #84: @3 = (@3*@6) */
  w3 *= w6;
  /* #85: @6 = cos(@2) */
  w6 = cos( w2 );
  /* #86: @3 = (@3*@6) */
  w3 *= w6;
  /* #87: @6 = sin(@7) */
  w6 = sin( w7 );
  /* #88: @3 = (@3*@6) */
  w3 *= w6;
  /* #89: @0 = (@0+@3) */
  w0 += w3;
  /* #90: @3 = 49556514 */
  w3 = 49556514.;
  /* #91: @6 = sq(@1) */
  w6 = casadi_sq( w1 );
  /* #92: @3 = (@3*@6) */
  w3 *= w6;
  /* #93: @6 = cos(@2) */
  w6 = cos( w2 );
  /* #94: @3 = (@3*@6) */
  w3 *= w6;
  /* #95: @6 = cos(@7) */
  w6 = cos( w7 );
  /* #96: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #97: @3 = (@3*@6) */
  w3 *= w6;
  /* #98: @6 = sin(@2) */
  w6 = sin( w2 );
  /* #99: @3 = (@3*@6) */
  w3 *= w6;
  /* #100: @0 = (@0+@3) */
  w0 += w3;
  /* #101: @3 = 25067112 */
  w3 = 25067112.;
  /* #102: @6 = sq(@4) */
  w6 = casadi_sq( w4 );
  /* #103: @3 = (@3*@6) */
  w3 *= w6;
  /* #104: @6 = cos(@2) */
  w6 = cos( w2 );
  /* #105: @8 = 3 */
  w8 = 3.;
  /* #106: @6 = pow(@6,@8) */
  w6  = pow(w6,w8);
  /* #107: @3 = (@3*@6) */
  w3 *= w6;
  /* #108: @6 = cos(@7) */
  w6 = cos( w7 );
  /* #109: @3 = (@3*@6) */
  w3 *= w6;
  /* #110: @6 = sin(@2) */
  w6 = sin( w2 );
  /* #111: @3 = (@3*@6) */
  w3 *= w6;
  /* #112: @0 = (@0+@3) */
  w0 += w3;
  /* #113: @3 = 18340000 */
  w3 = 18340000.;
  /* #114: @6 = sq(@1) */
  w6 = casadi_sq( w1 );
  /* #115: @3 = (@3*@6) */
  w3 *= w6;
  /* #116: @6 = cos(@2) */
  w6 = cos( w2 );
  /* #117: @8 = 3 */
  w8 = 3.;
  /* #118: @6 = pow(@6,@8) */
  w6  = pow(w6,w8);
  /* #119: @3 = (@3*@6) */
  w3 *= w6;
  /* #120: @6 = cos(@7) */
  w6 = cos( w7 );
  /* #121: @3 = (@3*@6) */
  w3 *= w6;
  /* #122: @6 = sin(@7) */
  w6 = sin( w7 );
  /* #123: @3 = (@3*@6) */
  w3 *= w6;
  /* #124: @0 = (@0-@3) */
  w0 -= w3;
  /* #125: @3 = 6727112 */
  w3 = 6727112.;
  /* #126: @6 = sq(@1) */
  w6 = casadi_sq( w1 );
  /* #127: @3 = (@3*@6) */
  w3 *= w6;
  /* #128: @6 = cos(@2) */
  w6 = cos( w2 );
  /* #129: @3 = (@3*@6) */
  w3 *= w6;
  /* #130: @6 = sin(@2) */
  w6 = sin( w2 );
  /* #131: @3 = (@3*@6) */
  w3 *= w6;
  /* #132: @6 = sin(@7) */
  w6 = sin( w7 );
  /* #133: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #134: @3 = (@3*@6) */
  w3 *= w6;
  /* #135: @0 = (@0+@3) */
  w0 += w3;
  /* #136: @3 = 18340000 */
  w3 = 18340000.;
  /* #137: @6 = sq(@1) */
  w6 = casadi_sq( w1 );
  /* #138: @3 = (@3*@6) */
  w3 *= w6;
  /* #139: @6 = cos(@2) */
  w6 = cos( w2 );
  /* #140: @3 = (@3*@6) */
  w3 *= w6;
  /* #141: @6 = sin(@2) */
  w6 = sin( w2 );
  /* #142: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #143: @3 = (@3*@6) */
  w3 *= w6;
  /* #144: @6 = sin(@7) */
  w6 = sin( w7 );
  /* #145: @3 = (@3*@6) */
  w3 *= w6;
  /* #146: @0 = (@0+@3) */
  w0 += w3;
  /* #147: @3 = 136680000 */
  w3 = 136680000.;
  /* #148: @3 = (@3*@1) */
  w3 *= w1;
  /* #149: @3 = (@3*@4) */
  w3 *= w4;
  /* #150: @6 = cos(@2) */
  w6 = cos( w2 );
  /* #151: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #152: @3 = (@3*@6) */
  w3 *= w6;
  /* #153: @6 = sin(@2) */
  w6 = sin( w2 );
  /* #154: @3 = (@3*@6) */
  w3 *= w6;
  /* #155: @0 = (@0+@3) */
  w0 += w3;
  /* #156: @3 = 25067112 */
  w3 = 25067112.;
  /* #157: @6 = sq(@1) */
  w6 = casadi_sq( w1 );
  /* #158: @3 = (@3*@6) */
  w3 *= w6;
  /* #159: @6 = cos(@2) */
  w6 = cos( w2 );
  /* #160: @8 = 3 */
  w8 = 3.;
  /* #161: @6 = pow(@6,@8) */
  w6  = pow(w6,w8);
  /* #162: @3 = (@3*@6) */
  w3 *= w6;
  /* #163: @6 = cos(@7) */
  w6 = cos( w7 );
  /* #164: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #165: @3 = (@3*@6) */
  w3 *= w6;
  /* #166: @6 = sin(@2) */
  w6 = sin( w2 );
  /* #167: @3 = (@3*@6) */
  w3 *= w6;
  /* #168: @0 = (@0-@3) */
  w0 -= w3;
  /* #169: @3 = 18340000 */
  w3 = 18340000.;
  /* #170: @3 = (@3*@5) */
  w3 *= w5;
  /* #171: @5 = cos(@2) */
  w5 = cos( w2 );
  /* #172: @3 = (@3*@5) */
  w3 *= w5;
  /* #173: @5 = sin(@2) */
  w5 = sin( w2 );
  /* #174: @3 = (@3*@5) */
  w3 *= w5;
  /* #175: @5 = sin(@7) */
  w5 = sin( w7 );
  /* #176: @3 = (@3*@5) */
  w3 *= w5;
  /* #177: @0 = (@0-@3) */
  w0 -= w3;
  /* #178: @3 = 13454224 */
  w3 = 13454224.;
  /* #179: @5 = sq(@1) */
  w5 = casadi_sq( w1 );
  /* #180: @3 = (@3*@5) */
  w3 *= w5;
  /* #181: @5 = cos(@2) */
  w5 = cos( w2 );
  /* #182: @6 = 3 */
  w6 = 3.;
  /* #183: @5 = pow(@5,@6) */
  w5  = pow(w5,w6);
  /* #184: @3 = (@3*@5) */
  w3 *= w5;
  /* #185: @5 = sin(@2) */
  w5 = sin( w2 );
  /* #186: @3 = (@3*@5) */
  w3 *= w5;
  /* #187: @5 = sin(@7) */
  w5 = sin( w7 );
  /* #188: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #189: @3 = (@3*@5) */
  w3 *= w5;
  /* #190: @0 = (@0-@3) */
  w0 -= w3;
  /* #191: @3 = 25067112 */
  w3 = 25067112.;
  /* #192: @3 = (@3*@1) */
  w3 *= w1;
  /* #193: @3 = (@3*@4) */
  w3 *= w4;
  /* #194: @5 = (2.*@7) */
  w5 = (2.* w7 );
  /* #195: @5 = sin(@5) */
  w5 = sin( w5 );
  /* #196: @3 = (@3*@5) */
  w3 *= w5;
  /* #197: @5 = cos(@2) */
  w5 = cos( w2 );
  /* #198: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #199: @3 = (@3*@5) */
  w3 *= w5;
  /* #200: @0 = (@0+@3) */
  w0 += w3;
  /* #201: @3 = 49556514 */
  w3 = 49556514.;
  /* #202: @5 = sq(@4) */
  w5 = casadi_sq( w4 );
  /* #203: @3 = (@3*@5) */
  w3 *= w5;
  /* #204: @5 = cos(@2) */
  w5 = cos( w2 );
  /* #205: @3 = (@3*@5) */
  w3 *= w5;
  /* #206: @5 = cos(@7) */
  w5 = cos( w7 );
  /* #207: @3 = (@3*@5) */
  w3 *= w5;
  /* #208: @5 = sin(@2) */
  w5 = sin( w2 );
  /* #209: @3 = (@3*@5) */
  w3 *= w5;
  /* #210: @0 = (@0-@3) */
  w0 -= w3;
  /* #211: @3 = 18340000 */
  w3 = 18340000.;
  /* #212: @5 = sq(@1) */
  w5 = casadi_sq( w1 );
  /* #213: @3 = (@3*@5) */
  w3 *= w5;
  /* #214: @5 = cos(@2) */
  w5 = cos( w2 );
  /* #215: @3 = (@3*@5) */
  w3 *= w5;
  /* #216: @5 = cos(@7) */
  w5 = cos( w7 );
  /* #217: @3 = (@3*@5) */
  w3 *= w5;
  /* #218: @5 = sin(@7) */
  w5 = sin( w7 );
  /* #219: @3 = (@3*@5) */
  w3 *= w5;
  /* #220: @0 = (@0+@3) */
  w0 += w3;
  /* #221: @3 = 99113028 */
  w3 = 99113028.;
  /* #222: @3 = (@3*@1) */
  w3 *= w1;
  /* #223: @3 = (@3*@4) */
  w3 *= w4;
  /* #224: @5 = cos(@2) */
  w5 = cos( w2 );
  /* #225: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #226: @3 = (@3*@5) */
  w3 *= w5;
  /* #227: @5 = cos(@7) */
  w5 = cos( w7 );
  /* #228: @3 = (@3*@5) */
  w3 *= w5;
  /* #229: @5 = sin(@7) */
  w5 = sin( w7 );
  /* #230: @3 = (@3*@5) */
  w3 *= w5;
  /* #231: @0 = (@0+@3) */
  w0 += w3;
  /* #232: @3 = 50134224 */
  w3 = 50134224.;
  /* #233: @3 = (@3*@1) */
  w3 *= w1;
  /* #234: @3 = (@3*@4) */
  w3 *= w4;
  /* #235: @5 = cos(@2) */
  w5 = cos( w2 );
  /* #236: @6 = 4 */
  w6 = 4.;
  /* #237: @5 = pow(@5,@6) */
  w5  = pow(w5,w6);
  /* #238: @3 = (@3*@5) */
  w3 *= w5;
  /* #239: @5 = cos(@7) */
  w5 = cos( w7 );
  /* #240: @3 = (@3*@5) */
  w3 *= w5;
  /* #241: @5 = sin(@7) */
  w5 = sin( w7 );
  /* #242: @3 = (@3*@5) */
  w3 *= w5;
  /* #243: @0 = (@0-@3) */
  w0 -= w3;
  /* #244: @3 = 6727112 */
  w3 = 6727112.;
  /* #245: @5 = sq(@1) */
  w5 = casadi_sq( w1 );
  /* #246: @3 = (@3*@5) */
  w3 *= w5;
  /* #247: @5 = cos(@2) */
  w5 = cos( w2 );
  /* #248: @6 = 3 */
  w6 = 3.;
  /* #249: @5 = pow(@5,@6) */
  w5  = pow(w5,w6);
  /* #250: @3 = (@3*@5) */
  w3 *= w5;
  /* #251: @5 = cos(@7) */
  w5 = cos( w7 );
  /* #252: @3 = (@3*@5) */
  w3 *= w5;
  /* #253: @5 = sin(@2) */
  w5 = sin( w2 );
  /* #254: @3 = (@3*@5) */
  w3 *= w5;
  /* #255: @5 = sin(@7) */
  w5 = sin( w7 );
  /* #256: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #257: @3 = (@3*@5) */
  w3 *= w5;
  /* #258: @0 = (@0-@3) */
  w0 -= w3;
  /* #259: @3 = 50134224 */
  w3 = 50134224.;
  /* #260: @3 = (@3*@1) */
  w3 *= w1;
  /* #261: @3 = (@3*@4) */
  w3 *= w4;
  /* #262: @4 = cos(@2) */
  w4 = cos( w2 );
  /* #263: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #264: @3 = (@3*@4) */
  w3 *= w4;
  /* #265: @4 = sin(@2) */
  w4 = sin( w2 );
  /* #266: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #267: @3 = (@3*@4) */
  w3 *= w4;
  /* #268: @4 = sin(@7) */
  w4 = sin( w7 );
  /* #269: @3 = (@3*@4) */
  w3 *= w4;
  /* #270: @0 = (@0+@3) */
  w0 += w3;
  /* #271: @3 = 6727112 */
  w3 = 6727112.;
  /* #272: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #273: @3 = (@3*@1) */
  w3 *= w1;
  /* #274: @1 = cos(@2) */
  w1 = cos( w2 );
  /* #275: @3 = (@3*@1) */
  w3 *= w1;
  /* #276: @1 = cos(@7) */
  w1 = cos( w7 );
  /* #277: @3 = (@3*@1) */
  w3 *= w1;
  /* #278: @1 = sin(@2) */
  w1 = sin( w2 );
  /* #279: @3 = (@3*@1) */
  w3 *= w1;
  /* #280: @1 = sin(@7) */
  w1 = sin( w7 );
  /* #281: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #282: @3 = (@3*@1) */
  w3 *= w1;
  /* #283: @0 = (@0+@3) */
  w0 += w3;
  /* #284: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #285: @3 = 137744656 */
  w3 = 137744656.;
  /* #286: @1 = cos(@2) */
  w1 = cos( w2 );
  /* #287: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #288: @3 = (@3*@1) */
  w3 *= w1;
  /* #289: @1 = 50134224 */
  w1 = 50134224.;
  /* #290: @4 = cos(@2) */
  w4 = cos( w2 );
  /* #291: @5 = 4 */
  w5 = 4.;
  /* #292: @4 = pow(@4,@5) */
  w4  = pow(w4,w5);
  /* #293: @1 = (@1*@4) */
  w1 *= w4;
  /* #294: @3 = (@3+@1) */
  w3 += w1;
  /* #295: @1 = 99113028 */
  w1 = 99113028.;
  /* #296: @4 = cos(@7) */
  w4 = cos( w7 );
  /* #297: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #298: @1 = (@1*@4) */
  w1 *= w4;
  /* #299: @3 = (@3-@1) */
  w3 -= w1;
  /* #300: @1 = 149247252 */
  w1 = 149247252.;
  /* #301: @4 = cos(@2) */
  w4 = cos( w2 );
  /* #302: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #303: @1 = (@1*@4) */
  w1 *= w4;
  /* #304: @4 = cos(@7) */
  w4 = cos( w7 );
  /* #305: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #306: @1 = (@1*@4) */
  w1 *= w4;
  /* #307: @3 = (@3+@1) */
  w3 += w1;
  /* #308: @1 = 50134224 */
  w1 = 50134224.;
  /* #309: @4 = cos(@2) */
  w4 = cos( w2 );
  /* #310: @5 = 4 */
  w5 = 4.;
  /* #311: @4 = pow(@4,@5) */
  w4  = pow(w4,w5);
  /* #312: @1 = (@1*@4) */
  w1 *= w4;
  /* #313: @4 = cos(@7) */
  w4 = cos( w7 );
  /* #314: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #315: @1 = (@1*@4) */
  w1 *= w4;
  /* #316: @3 = (@3-@1) */
  w3 -= w1;
  /* #317: @1 = 13454224 */
  w1 = 13454224.;
  /* #318: @4 = cos(@2) */
  w4 = cos( w2 );
  /* #319: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #320: @1 = (@1*@4) */
  w1 *= w4;
  /* #321: @4 = sin(@2) */
  w4 = sin( w2 );
  /* #322: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #323: @1 = (@1*@4) */
  w1 *= w4;
  /* #324: @4 = sin(@7) */
  w4 = sin( w7 );
  /* #325: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #326: @1 = (@1*@4) */
  w1 *= w4;
  /* #327: @3 = (@3+@1) */
  w3 += w1;
  /* #328: @1 = 73360000 */
  w1 = 73360000.;
  /* #329: @4 = cos(@2) */
  w4 = cos( w2 );
  /* #330: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #331: @1 = (@1*@4) */
  w1 *= w4;
  /* #332: @2 = sin(@2) */
  w2 = sin( w2 );
  /* #333: @1 = (@1*@2) */
  w1 *= w2;
  /* #334: @7 = sin(@7) */
  w7 = sin( w7 );
  /* #335: @1 = (@1*@7) */
  w1 *= w7;
  /* #336: @3 = (@3+@1) */
  w3 += w1;
  /* #337: @1 = 270561273 */
  w1 = 270561273.;
  /* #338: @3 = (@3-@1) */
  w3 -= w1;
  /* #339: @0 = (@0/@3) */
  w0 /= w3;
  /* #340: @3 = input[5][0] */
  w3 = arg[5] ? arg[5] : 0;
  /* #341: @0 = (@0-@3) */
  w0 -= w3;
  /* #342: output[0][0] = @0 */
  if (res[0]) res[0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int f2(casadi_real* arg, casadi_real* res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f2_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f2_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f2_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f2_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f2_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f2_incref(void) {
}

CASADI_SYMBOL_EXPORT void f2_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f2_n_in(void) { return 8;}

CASADI_SYMBOL_EXPORT casadi_int f2_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f2_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f2_name_in(casadi_int i){
  switch (i) {
    case 0: return "theta";
    case 1: return "dtheta";
    case 2: return "ddtheta";
    case 3: return "phi";
    case 4: return "dphi";
    case 5: return "ddphi";
    case 6: return "tau";
    case 7: return "g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f2_name_out(casadi_int i){
  switch (i) {
    case 0: return "f2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f2_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f2_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f2_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 9;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
